apiVersion: gravitee.io/v1alpha1
kind: ApiV4Definition
metadata:
  name: generated-crd
  namespace: default
spec:
  name: Petstore API
  description: A sample API to illustrate OpenAPI concepts
  version: 1.0.0
  type: PROXY
  lifecycleState: PUBLISHED
  visibility: PUBLIC
  definitionContext:
    origin: KUBERNETES
    syncFrom: MANAGEMENT
  contextRef:
    name: apim-example-context
    namespace: default
  listeners:
    - type: HTTP
      paths:
        - path: /petstore
      entrypoints:
        - type: http-proxy
          qos: AUTO
  endpointGroups:
    - name: Default HTTP proxy group
      type: http-proxy
      endpoints:
        - name: Default HTTP proxy
          type: http-proxy
          inheritConfiguration: false
          configuration:
            target: https://api.gravitee.io/echo
          secondary: false
  flowExecution:
    mode: DEFAULT
    matchRequired: false
  plans:
    API_KEY:
      name: API Key plan
      description: API key plan needs a key to authenticate
      security:
        type: API_KEY
      flows:
        - name: Rate Limiting Flow
          enabled: true
          selectors:
            - type: HTTP
              path: /
              pathOperator: EQUALS
              methods: []
          request:
            - name: Rate Limit
              description: Standard rate limiting of 5 requests per minute (per consumer)
              enabled: true
              policy: rate-limit
              configuration:
                async: false
                addHeaders: true
                rate:
                  useKeyOnly: false
                  periodTime: 1
                  limit: 5
                  periodTimeUnit: MINUTES
          response: []
          subscribe: []
          publish: []
  flows:
    - name: OpenAPI Specification Validation
      enabled: true
      selectors:
        - type: HTTP
          path: /
          pathOperator: STARTS_WITH
      request:
        - name: OpenAPI Specification Validation
          enabled: true
          policy: oas-validation
          configuration:
            resourceName: OpenAPI Specification
      response:
        - name: OpenAPI Specification Validation
          enabled: true
          policy: oas-validation
          configuration:
            resourceName: OpenAPI Specification
    - name: Root path for only Echo response
      enabled: true
      selectors:
        - type: HTTP
          path: /
          pathOperator: EQUALS
          methods:
            - GET
    - name: Returns a list of stuff
      enabled: true
      selectors:
        - type: HTTP
          path: /list
          pathOperator: EQUALS
          methods:
            - GET
    - name: Create a new Pet
      enabled: true
      selectors:
        - type: HTTP
          path: /pets
          pathOperator: EQUALS
          methods:
            - POST
  resources:
    - name: OpenAPI Specification
      type: content-provider-inline-resource
      configuration:
        content: |
          openapi: 3.1.0 
          info: 
            version: 1.0.0 
            title: Petstore API 
            description: A sample API to illustrate OpenAPI concepts 
          paths: 
            /: 
              get: 
                description: Root path for only Echo response 
                responses: 
                  '200': 
                    description: Successful response 
                    content: 
                      application/json: 
                        schema: 
                          type: object 
                          properties: 
                            bodySize: 
                              type: string 
                              description: Displays the size of the original request body. 
                            headers: 
                              type: string 
                              description: Displays all the headers from the original request. 
                            query_params: 
                              type: string 
                              description: >- 
                                Displays all the query parameters from the original 
                                request. 
            /list: 
              get: 
                description: Returns a list of stuff 
                responses: 
                  '200': 
                    description: Successful response. 
            /pets: 
              post: 
                description: Create a new Pet 
                responses: 
                  '201': 
                    description: Created 
      enabled: true
    - name: Gravitee IdP2
      type: oauth2-am-resource
      configuration:
        serverURL: https://demo-am-gateway.brent.gravitee.xyz
        useSystemProxy: false
        version: V3_X
        securityDomain: brentdomain
        clientId: b76a525f-9d95-4aa1-aa52-5f9d952aa17d
        clientSecret: ...
        userClaim: sub
  pages:
    OpenAPIDoc:
      name: OpenAPI Specification Documentation
      type: SWAGGER
      published: true
      visibility: PUBLIC
      configuration:
        viewer: Swagger
        entrypointAsBasePath: 'false'
        entrypointsAsServers: 'true'
        tryIt: 'true'
        tryItAnonymous: 'true'
        showURL: 'true'
      content: |
        openapi: 3.1.0 
        info: 
          version: 1.0.0 
          title: Petstore API 
          description: A sample API to illustrate OpenAPI concepts 
        paths: 
          /: 
            get: 
              description: Root path for only Echo response 
              responses: 
                '200': 
                  description: Successful response 
                  content: 
                    application/json: 
                      schema: 
                        type: object 
                        properties: 
                          bodySize: 
                            type: string 
                            description: Displays the size of the original request body. 
                          headers: 
                            type: string 
                            description: Displays all the headers from the original request. 
                          query_params: 
                            type: string 
                            description: >- 
                              Displays all the query parameters from the original 
                              request. 
          /list: 
            get: 
              description: Returns a list of stuff 
              responses: 
                '200': 
                  description: Successful response. 
          /pets: 
            post: 
              description: Create a new Pet 
              responses: 
                '201': 
                  description: Created 
